title: Home SOC Lab Setup Project
description: Use to develop skills in configuring a Security Operations Center (SOC) for hands-on practice with tools for monitoring, detecting, and responding to threats.
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
